### ISSUE TITLE
Youtube streaming trouble  

### ISSUE THREAD

**Issue by OleksandrAndro** [octiplex/Android-RTMP-Muxer#8]
I trying to stream video to Youtube, but getting error:

11-03 19:58:48.400 1861-1881/com.wzh.accmonite D/ACC Server: Acc Detection High true
11-03 19:58:48.416 25671-25731/com.jiangdg.usbcamera D/RtmpMuxer: onReaderError
    java.io.IOException: Unknown basic header: 66
        at com.octiplex.android.rtmp.io.RtmpReader.run(RtmpReader.java:205)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by benoitletondor** [comment]
Hey @OleksandrAndro 

Sorry about that, I'm not working anymore on the project so I can't really help you.

Maybe you check the RFC and find out more: "5.3.1.1. Chunk Basic Header" section of https://wwwimages2.adobe.com/content/dam/acom/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf
